[project]
name = "traefik-example"
version = "0.1.0"
description = "A simple service which uses traefik proxy"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.118.0",
]
